### ISSUE TITLE
Haydi Evimizdeki İnterneti Koruyalım

### ISSUE THREAD

**Issue by MertcanGokgoz** [MertcanGokgoz/mertcangokgoz.github.io#18]

**Comment by MertcanGokgoz** [comment]
para kaç sistem toplam ?

**Comment by geekdinazor** [comment]
biz fakirler için ne önerirsin mertcan kardeş ?

**Comment by MertcanGokgoz** [comment]
Hangi konuda olduğuna bağlı firewall için ise pfsense olur opensense olur. Benim gibi URL Filtering önemli ise ama paraya kıymak gerekiyor.

Yoksa kuraldan link vs kaçıyor hoş olmaz tabi :1st_place_medal:

**Comment by ahmethakanbesel** [comment]
i7700K biraz fazla değil mi?

**Comment by MertcanGokgoz** [comment]
@ahmethakanbesel Testler ve yapacaklarımdan sonra bu makina ile oyun oynamayı planlıyorum :+1: Tabi hala test ediyorum.
