### ISSUE TITLE
Linux'de UID ve GID Değişikliği

### ISSUE THREAD

**Issue by MertcanGokgoz** [MertcanGokgoz/mertcangokgoz.github.io#23]

**Comment by geekdinazor** [comment]
Bunu 0 yaparsak root olur muyuz yoksa root'a şirk koşmaktan kill olunca /dev/urandom'a mı gideriz ? :smile_cat:

**Comment by MertcanGokgoz** [comment]
0 demek root demek değildir. Çekirdek 0 uid li arkadaşı root olarak ayırmıştır ancak sen bunları 0 yaptın diye gidip root yetkisini sana vermez :D çünkü bu arkadaşlarımız bunu düşünmüş. 0 her zaman kök kullanıcıyı işaret eder ancak, sen 0 yaptın diye root olmaz. root kardeş sadece bir isimdir. yetkilendirilmez ise normal bir kullanıcı gibi takılabilir.

ALL = (ALL:ALL) ALL

Komutunu vermediğin sürece sorun yaşatmaz lakin sistemin içine etme olasılığın %90 artar bazı uygulamalar çalışmaz. yani not recommended
